FROM node:16.10.0

RUN apt-get update && apt-get install -y \
       build-essential \
       libssl-dev

RUN mkdir -p /app

COPY . /var/www/backend
WORKDIR /var/www/backend

EXPOSE 5000

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN yarn
RUN npm run build
CMD npm run typeorm:run && npm run start:prod