version: '3.4'

services:
  biostasis_app:
    env_file:
      - .env
    build: .
    container_name: biostasis_app
    ports:
      - 17001:5000
    tty: true
    links:
      - biostasis_database
    depends_on:
      - biostasis_database
    environment:
      - APP_PORT=5000
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=biostasis
      - DB_HOST=biostasis_database
      - DB_PORT=3306
      - NODE_ENV=development
      - GLOBAL_PREFIX=${GLOBAL_PREFIX}
  biostasis_database:
    env_file:
      - .env
    image: mysql:8.0.20
    container_name: biostasis_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: biostasts
    volumes:
      - /home/jenkins/biostasis/backend/db/mysql/:/var/lib/mysql
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
