FROM node:15.0.1

RUN apt-get update && apt-get install -y \
       nano \
       build-essential \
       libssl-dev

RUN mkdir -p /app

COPY . /var/www/backend
WORKDIR /var/www/backend

RUN ls
RUN pwd

EXPOSE 5000

RUN yarn
RUN npm run build
CMD npm run typeorm:run && npm run start:prod
