export enum MESSAGE_TYPE {
  EMERGENCY_PULSE_BASED_CHECK = 'EMERGENCY_PULSE_BASED_CHECK',
  EMERGENCY_TIME_BASED_CHECK = 'EMERGENCY_TIME_BASED_CHECK',
  EMERGENCY_ALERT = 'EMERGENCY_ALERT',
  TIME_SLOT_NOTIFICATION = 'TIME_SLOT_NOTIFICATION',
}
