import * as Joi from 'joi';

export const configSchema: Joi.ObjectSchema = Joi.object({
  APP_PORT: Joi.number(),
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'stage', 'test')
    .default('development'),
  DB_USERNAME: Joi.string(),
  DB_DATABASE: Joi.string(),
  DB_PASSWORD: Joi.string(),
  DB_HOST: Joi.string(),
  DB_PORT: Joi.number().default(3306),
  GLOBAL_PREFIX: Joi.string(),
  COGNITO_ACCESS_KEY_ID: Joi.string().optional().allow(''),
  COGNITO_SECRET_ACCESS_KEY: Joi.string().optional().allow(''),
  COGNITO_USER_POOL_ID: Joi.string(),
  COGNITO_CLIENT_ID: Joi.string(),
  COGNITO_REGION: Joi.string(),
  BACKEND_URL: Joi.string(),
  MAILJET_API_KEY: Joi.string(),
  MAILJET_API_SECRET: Joi.string(),
  MAILJET_EMAIL: Joi.string(),
  MAILJET_USERNAME: Joi.string(),
  TWILIO_ACCOUNT_SID: Joi.string(),
  TWILIO_AUTH_TOKEN: Joi.string(),
  TWILIO_PHONE_NUMBER: Joi.string(),
  REDIS_SCHEMA: Joi.string(),
  REDIS_USER: Joi.string(),
  REDIS_HOST: Joi.string(),
  REDIS_PORT: Joi.number(),
  REDIS_PASSWORD: Joi.string(),
  S3_ACCESS_KEY_ID: Joi.string().optional().allow(''),
  S3_SECRET_ACCESS_KEY: Joi.string().optional().allow(''),
  S3_BUCKET: Joi.string(),
  S3_URL: Joi.string(),
  FIREBASE_ACCOUNT_KEY: Joi.string(),
  ENCRYPTION_IV: Joi.string().required(),
  ENCRYPTION_KEY: Joi.string().required(),
}).options({ allowUnknown: true, presence: 'required' });
